// flow-typed signature: 6f88bea5fc44a92f033e534d237cf9fa
// flow-typed version: <<STUB>>/react-storybook-addon-backgrounds_v^0.0.7/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-storybook-addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-storybook-addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-storybook-addon-backgrounds/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/__tests__/BackgroundPanel' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/__tests__/Swatch' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/BackgroundPanel' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/index.story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/dist/Swatch' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/docs/static/manager.bundle' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/docs/static/preview.bundle' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-backgrounds/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-storybook-addon-backgrounds/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/coverage/lcov-report/prettify'>;
}
declare module 'react-storybook-addon-backgrounds/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/coverage/lcov-report/sorter'>;
}
declare module 'react-storybook-addon-backgrounds/dist/__tests__/BackgroundPanel.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/__tests__/BackgroundPanel'>;
}
declare module 'react-storybook-addon-backgrounds/dist/__tests__/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/__tests__/index'>;
}
declare module 'react-storybook-addon-backgrounds/dist/__tests__/Swatch.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/__tests__/Swatch'>;
}
declare module 'react-storybook-addon-backgrounds/dist/BackgroundPanel.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/BackgroundPanel'>;
}
declare module 'react-storybook-addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/index'>;
}
declare module 'react-storybook-addon-backgrounds/dist/index.story.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/index.story'>;
}
declare module 'react-storybook-addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/register'>;
}
declare module 'react-storybook-addon-backgrounds/dist/Swatch.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/dist/Swatch'>;
}
declare module 'react-storybook-addon-backgrounds/docs/static/manager.bundle.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/docs/static/manager.bundle'>;
}
declare module 'react-storybook-addon-backgrounds/docs/static/preview.bundle.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/docs/static/preview.bundle'>;
}
declare module 'react-storybook-addon-backgrounds/register.js' {
  declare module.exports: $Exports<'react-storybook-addon-backgrounds/register'>;
}
