// flow-typed signature: 062daa5f2e9685aa49a2fadca9b15058
// flow-typed version: <<STUB>>/@kadira/react-storybook-addon-info_v^3.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/react-storybook-addon-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/react-storybook-addon-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/react-storybook-addon-info/dist/components/markdown/code' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/markdown/htags' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/markdown/index' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/markdown/text' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/Node' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/Props' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/PropTable' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/PropVal' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/Story' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/components/theme' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/example/Button' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/example/story' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/markdown/code' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/markdown/htags' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/markdown/index' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/markdown/text' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/Node' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/Props' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/PropTable' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/PropVal' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/Story' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/components/theme' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/index' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-addon-info/src/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/react-storybook-addon-info/dist/components/markdown/code.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/markdown/code'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/markdown/htags.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/markdown/htags'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/markdown/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/markdown/index'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/markdown/text.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/markdown/text'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/Node.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/Node'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/Props.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/Props'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/PropTable.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/PropTable'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/PropVal.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/PropVal'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/Story.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/Story'>;
}
declare module '@kadira/react-storybook-addon-info/dist/components/theme.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/components/theme'>;
}
declare module '@kadira/react-storybook-addon-info/dist/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/dist/index'>;
}
declare module '@kadira/react-storybook-addon-info/example/Button.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/example/Button'>;
}
declare module '@kadira/react-storybook-addon-info/example/story.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/example/story'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/markdown/code.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/markdown/code'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/markdown/htags.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/markdown/htags'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/markdown/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/markdown/index'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/markdown/text.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/markdown/text'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/Node.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/Node'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/Props.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/Props'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/PropTable.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/PropTable'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/PropVal.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/PropVal'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/Story.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/Story'>;
}
declare module '@kadira/react-storybook-addon-info/src/components/theme.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/components/theme'>;
}
declare module '@kadira/react-storybook-addon-info/src/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/index'>;
}
declare module '@kadira/react-storybook-addon-info/src/tests/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-addon-info/src/tests/index'>;
}
