// flow-typed signature: 27fb46095bb74f8a92984f25fd771476
// flow-typed version: <<STUB>>/@kadira/storybook-addon-options_v^1.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-addon-options'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-addon-options' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-addon-options/dist/manager/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/dist/preview/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/dist/shared/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/manager' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/preview' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/register' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/src/manager/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/src/preview/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-options/src/shared/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-addon-options/dist/manager/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/dist/manager/index'>;
}
declare module '@kadira/storybook-addon-options/dist/preview/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/dist/preview/index'>;
}
declare module '@kadira/storybook-addon-options/dist/shared/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/dist/shared/index'>;
}
declare module '@kadira/storybook-addon-options/manager.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/manager'>;
}
declare module '@kadira/storybook-addon-options/preview.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/preview'>;
}
declare module '@kadira/storybook-addon-options/register.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/register'>;
}
declare module '@kadira/storybook-addon-options/src/manager/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/src/manager/index'>;
}
declare module '@kadira/storybook-addon-options/src/preview/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/src/preview/index'>;
}
declare module '@kadira/storybook-addon-options/src/shared/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-options/src/shared/index'>;
}
